# Generated by Django 4.2.2 on 2024-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
