# Generated by Django 4.2.2 on 2024-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("toppage", "0002_member"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
